### ISSUE TITLE
Docs feedback: /operators-guide/deploy-kubernetes/_index.md

### ISSUE THREAD

**Issue by Siebjee** [grafana/phlare#398]
On the docs there is a snippet to configure the grafana datasource. But the `url`'s value contains a dot (.) too much.

Current:
```yaml
datasources:
  phlare.yaml:
   apiVersion: 1
   datasources:
   - name: Phlare
     type: phlare
     uid: phlare-test
     url: http://phlare-querier.phlare-test.svc.cluster.local.:4100/
YAML
```

Suggestion:
```yaml
datasources:
  phlare.yaml:
   apiVersion: 1
   datasources:
   - name: Phlare
     type: phlare
     uid: phlare-test
     url: http://phlare-querier.phlare-test.svc.cluster.local:4100/
YAML
````
