### ISSUE TITLE
cannot find flamegraph when explore from grafana-phlare-datasource

### ISSUE THREAD

**Issue by zhuw0312** [grafana/phlare#419]
### phlare  config
```
multitenancy_enabled: false
target: all
server:
  grpc_listen_port: 9097
  http_listen_address: 0.0.0.0
ingester:
  lifecycler:
    address: 127.0.0.1
    tokens_file_path: ./tokens
    ring:
      kvstore:
        store: consul
        prefix: "collectors/"
        consul:
          host: "localhost:8500"
memberlist:
  node_name: phlare-test
phlaredb:
  data_path: "./data"
storage:
  backend: filesystem
scrape_configs:
  - job_name: "phlare"
    scrape_interval: "15s"
    static_configs:
      - targets: ["127.0.0.1:4100"]
```

#### please  help me .tks
