### ISSUE TITLE
cant change all instance_interface_names params

### ISSUE THREAD

**Issue by youngpabl0** [grafana/phlare#553]
hello guyz, really appreciate for your OSS products, i have question / found a bug:
``distributor.ring.instance_interface_names`` - phlare have this param in /api/v1/status/config but i cant change it, anywhere - cli params / yaml config params...
``query_scheduler.ring.instance_interface_names`` - same case
``overrides_exporter`` - what is this part of config from api? cause i found ``instance_interface_names`` in ``overrides_exporter.ring.instance_interface_names``
https://grafana.com/docs/phlare/latest/operators-guide/configure/reference-configuration-parameters/ i was looking here, fix my link if i get wrong please
why i'm asking? i run phlare on pure docker with network=host, i want to bind all phlare microservices to 127.0.0.1 and share public only what i want via nginx proxy
thanks a lot!

**Comment by cyriltovena** [comment]
Those interface are used to form a ring across pods, so they can't bind to 127.0.0.1, by default it uses a private network.

What you're looking for is more:

```
# HTTP server listen address.
# CLI flag: -server.http-listen-address
[http_listen_address: <string> | default = ""]
```

On the server block.

**Comment by youngpabl0** [comment]
> Those interface are used to form a ring across pods,it's not about binding, it's about which interface to use to find the current instance IP and advertise to others, by default it uses a private network.
> 
> What you're looking for is more:
> 
> ```
> # HTTP server listen address.
> # CLI flag: -server.http-listen-address
> [http_listen_address: <string> | default = ""]
> ```
> 
> On the server block.

docker version:
```
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.12
  GitCommit:        a05d175400b1145e5e6a735a6710579d181e7fb0
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
phlare version 0.5.1, .service (user 1001 = phlare):
```
[Unit]
Description="Grafana Phlare - continious profiling"
Documentation=https://grafana.com/docs/phlare/latest/release-notes/
Wants=network-online.target
After=network-online.target
Requires=docker.service

[Service]
ExecStart=/usr/bin/docker run \
    --name %N \
    --rm \
    --net=host \
    --user=1001 \
    --log-opt labels=app \
    --label app=phlare \
    -v /var/storage/phlare/phlare.yml:/etc/phlare.yaml \
    -v /var/storage/phlare/data:/data \
    grafana/phlare:0.5.1 \
    -config.file=/etc/phlare.yaml \
    -target=all \
    -memberlist.bind-addr=127.0.0.1 \
    -memberlist.advertise-addr=127.0.0.1
ExecStop=/usr/bin/docker stop -t 300 %N

[Install]
WantedBy=multi-user.target
```
phlare.yml:
```
server:
  http_listen_port: 4100
  http_listen_address: 127.0.0.1
  grpc_listen_port: 4101
  grpc_listen_address: 127.0.0.1
  log_level: debug

ingester:
  lifecycler:
    interface_names: ["lo"]
    address: 127.0.0.1
    ring:
      kvstore:
        store: "inmemory"

distributor:
  ring:
    kvstore:
      store: "inmemory"
  #interface_names: ["lo"]

query_scheduler:
  #interface_names: ["lo"]
  #address: 127.0.0.1
  ring:
    kvstore:
      store: "inmemory"

frontend:
  instance_interface_names: ["lo"]
  address: 127.0.0.1

#memberlist:
#  advertise_addr: 127.0.0.1
#  bind_addr: ["127.0.0.1"]

scrape_configs:
  - job_name: "phlare"
    scrape_interval: "15s"
    static_configs:
      - targets: ["127.0.0.1:4100"]

  - job_name: "victoria-metrics"
    scrape_interval: "15s"
    static_configs:
      - targets: ["127.0.0.1:8429"]
```
and not all server ips is 127.0.0.1 after that:
```
Mar 02 20:39:38 docker[1189005]: level=error caller=scheduler_processor.go:128 ts=2023-03-02T20:39:38.848973589Z component=querier-worker msg="error processing requests from scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.188.64.148:4100: connect: connection refused\"" addr=10.188.64.148:4100
Mar 02 20:39:39 docker[1189005]: level=error caller=frontend_scheduler_worker.go:285 ts=2023-03-02T20:39:39.007845952Z component=frontend msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.188.64.148:4100: connect: connection refused\"" addr=10.188.64.148:4100
```
and in `curl 127.0.0.1:4100/api/v1/status/config` answer on curl:
- `distributor.ring.instance_interface_names` are interfaces dat i cant change...
- `distributor.ring.instance_addr` is "" and i too cant change it by params / cli flags ([docs](https://grafana.com/docs/phlare/latest/operators-guide/configure/reference-configuration-parameters/#distributor))
- `frontend.scheduler_address`: "" - empty, cant change it by params / cli ([docs](https://grafana.com/docs/phlare/latest/operators-guide/configure/reference-configuration-parameters/#frontend_worker))
- `query_scheduler.ring.instance_interface_names` are interfaces dat i cant change too ([docs](https://grafana.com/docs/phlare/latest/operators-guide/configure/reference-configuration-parameters/#query_scheduler))
- `overrides_exporter` - what is part of configuration overrrides something?) i dont find anything in docs or issues / discussions / commits, help to undertsand please, cause it has instance_interface_names param too

i'v just think i must have configuration params for configure this addresses and thank you again!
